services:
    nginx:
        container_name: godlike-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        ports:
            - ${DOCKER_APP_PORT:-80}:80
        working_dir: /var/www
        volumes:
            - ./public/:/var/www/public
            - ./storage/:/var/www/storage
        networks:
            - godlike_network
        links:
            - app
        depends_on:
            - app
    app:
        container_name: godlike-app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        hostname: godlike-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www/
        environment:
            - DB_HOST=${DB_HOST:-postgres}
        ports:
            - 8080:8080
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - godlike_network

    postgres:
        container_name: godlike-postgres
        image: postgres
        volumes:
            - ./docker/db:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_DB: ${DB_DATABASE:-app}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            PGDATA: /data/postgres
        ports:
            - ${DOCKER_POSTGRES_PORT:-5432}:5432
        restart: unless-stopped
        networks:
            - godlike_network

networks:
    godlike_network:
        driver: bridge
        ipam:
            driver: default
            config:
                -  subnet: 192.168.7.0/24
